version: '3.7'

services:
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8080:8080"  # Spark Web UI
    networks:
      - spark-net
    volumes:
      - ./spark-conf:/opt/bitnami/spark/conf  # Mount thư mục cấu hình

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-net

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
    command: server /data
    ports:
      - "9000:9000"  # MinIO Web UI
    volumes:
      - minio-data:/data
    networks:
      - spark-net

volumes:
  minio-data:

networks:
  spark-net:
    driver: bridge
